from __future__ import annotations

import json

import pytest

from doc_dl.config import StatePaths
from doc_dl.errors import DocDlError
from doc_dl.providers.generic import GenericProvider
from doc_dl.providers.googledrive import GoogleDriveProvider
from doc_dl.providers.registry import ProviderRegistry
from doc_dl.providers.scribd import ScribdProvider, _clean_scribd_title
from doc_dl.providers.slideshare import SlideShareProvider


def test_scribd_provider_normalizes_both_url_styles() -> None:
    provider = ScribdProvider()
    assert provider.normalize("https://www.scribd.com/doc/12345/a-title") == (
        "https://www.scribd.com/document/12345"
    )
    assert provider.browser_url("https://www.scribd.com/document/12345/a-title") == (
        "https://www.scribd.com/embeds/12345/content"
    )


def test_scribd_provider_recognizes_presentation_urls() -> None:
    provider = ScribdProvider()
    assert provider.match("https://www.scribd.com/presentation/12345/a-title") == 100
    assert provider.normalize("https://www.scribd.com/presentation/12345/a-title") == (
        "https://www.scribd.com/document/12345"
    )


def test_clean_scribd_title_strips_site_suffix() -> None:
    assert (
        _clean_scribd_title("Autogenerated 10-Page Scribd Document | PDF | Scribd | Document")
        == "Autogenerated 10-Page Scribd Document"
    )


def test_clean_scribd_title_unescapes_entities() -> None:
    assert _clean_scribd_title("Alice &amp; Bob | PDF | Scribd | Document") == "Alice & Bob"


def test_clean_scribd_title_returns_none_for_empty_result() -> None:
    assert _clean_scribd_title("   ") is None


class _FakeResponse:
    def __init__(self, ok: bool, text: str) -> None:
        self.ok = ok
        self._text = text

    def text(self) -> str:
        return self._text


class _FakeRequest:
    def __init__(self, response: _FakeResponse) -> None:
        self._response = response
        self.calls: list[str] = []

    def get(self, url: str, *, timeout: float) -> _FakeResponse:
        del timeout
        self.calls.append(url)
        return self._response


class _FakePage:
    def __init__(self, url: str, response: _FakeResponse) -> None:
        self.url = url
        self.request = _FakeRequest(response)


def test_page_title_fetches_real_document_page_title() -> None:
    provider = ScribdProvider()
    page = _FakePage(
        "https://www.scribd.com/embeds/959028055/content",
        _FakeResponse(True, "<title>Ten Page Sample | PDF | Scribd | Document</title>"),
    )

    assert provider.page_title(page) == "Ten Page Sample"
    assert page.request.calls == ["https://www.scribd.com/document/959028055"]


def test_page_title_returns_none_on_failed_response() -> None:
    provider = ScribdProvider()
    page = _FakePage(
        "https://www.scribd.com/embeds/959028055/content",
        _FakeResponse(False, ""),
    )

    assert provider.page_title(page) is None


def test_page_title_returns_none_for_non_scribd_url() -> None:
    provider = ScribdProvider()
    page = _FakePage("https://example.com/not-scribd", _FakeResponse(True, "<title>x</title>"))

    assert provider.page_title(page) is None


def test_registry_prefers_scribd_over_generic() -> None:
    provider = ProviderRegistry().select("https://www.scribd.com/document/12345/a-title")
    assert provider.name == "scribd"


def test_registry_prefers_scribd_for_presentation_urls() -> None:
    provider = ProviderRegistry().select("https://www.scribd.com/presentation/12345/a-title")
    assert provider.name == "scribd"


def test_profile_name_cannot_escape_state_root(tmp_path) -> None:
    paths = StatePaths(tmp_path)
    with pytest.raises(DocDlError) as raised:
        paths.profile("scribd", "../../escape")
    assert raised.value.identifier == "invalid_arguments"


def _slideshare_html(*, total_slides: int = 3) -> str:
    payload = {
        "props": {
            "pageProps": {
                "slideshow": {
                    "title": "Sample Deck",
                    "totalSlides": total_slides,
                    "slides": {
                        "host": "https://image.slidesharecdn.com",
                        "imageLocation": "abc123-deadbeef",
                        "title": "Sample-Deck",
                        "imageSizes": [
                            {"quality": 85, "width": 320, "format": "jpg"},
                            {"quality": 85, "width": 638, "format": "jpg"},
                            {"quality": 75, "width": 2048, "format": "webp"},
                        ],
                    },
                }
            }
        }
    }
    return f'<script id="__NEXT_DATA__" type="application/json">{json.dumps(payload)}</script>'


def test_slideshare_matches_slideshare_urls() -> None:
    provider = SlideShareProvider()
    assert provider.match("https://www.slideshare.net/slideshow/deck/123") == 100
    assert provider.match("https://example.com/not-slideshare") == 0


def test_slideshare_parses_image_pages_from_next_data() -> None:
    provider = SlideShareProvider()
    image_set = provider.image_pages_from_html(_slideshare_html(total_slides=3), "https://x")

    assert image_set is not None
    assert image_set.title == "Sample Deck"
    assert image_set.image_urls == [
        "https://image.slidesharecdn.com/abc123-deadbeef/75/Sample-Deck-1-2048.jpg",
        "https://image.slidesharecdn.com/abc123-deadbeef/75/Sample-Deck-2-2048.jpg",
        "https://image.slidesharecdn.com/abc123-deadbeef/75/Sample-Deck-3-2048.jpg",
    ]


def test_slideshare_picks_largest_available_width() -> None:
    provider = SlideShareProvider()
    image_set = provider.image_pages_from_html(_slideshare_html(total_slides=1), "https://x")

    assert image_set.image_urls[0].endswith("-2048.jpg")


def test_slideshare_returns_none_without_next_data() -> None:
    provider = SlideShareProvider()
    html = "<html><body>no data here</body></html>"
    assert provider.image_pages_from_html(html, "https://x") is None


def test_slideshare_returns_none_for_malformed_json() -> None:
    provider = SlideShareProvider()
    html = '<script id="__NEXT_DATA__" type="application/json">{not valid json</script>'
    assert provider.image_pages_from_html(html, "https://x") is None


def test_registry_selects_slideshare_over_generic() -> None:
    provider = ProviderRegistry().select("https://www.slideshare.net/slideshow/deck/123")
    assert provider.name == "slideshare"


def test_google_drive_normalizes_a_shared_file_view_link() -> None:
    provider = GoogleDriveProvider()
    assert (
        provider.normalize(
            "https://drive.google.com/file/d/0B9P1L--7Wd2vU3VUVlFnbTgtS2c/view?usp=sharing"
        )
        == "https://drive.google.com/uc?export=download&id=0B9P1L--7Wd2vU3VUVlFnbTgtS2c"
    )


def test_google_drive_preserves_the_resource_key() -> None:
    provider = GoogleDriveProvider()
    assert (
        provider.normalize("https://drive.google.com/file/d/abc123/view?resourcekey=0-testKey")
        == "https://drive.google.com/uc?export=download&id=abc123&resourcekey=0-testKey"
    )


def test_google_drive_accepts_open_and_uc_links() -> None:
    provider = GoogleDriveProvider()
    for url in (
        "https://drive.google.com/open?id=abc123",
        "https://drive.google.com/uc?export=download&id=abc123",
        "https://docs.google.com/uc?id=abc123",
    ):
        assert provider.match(url) == 100
        assert provider.normalize(url) == ("https://drive.google.com/uc?export=download&id=abc123")


def test_google_drive_ignores_unrelated_google_urls() -> None:
    provider = GoogleDriveProvider()
    assert provider.match("https://drive.google.com/drive/my-drive") == 0
    assert provider.match("https://example.com/file/d/abc123/view") == 0


def test_registry_selects_google_drive_over_generic() -> None:
    provider = ProviderRegistry().select("https://drive.google.com/file/d/abc123/view?usp=sharing")
    assert provider.name == "googledrive"


def test_generic_provider_does_not_rewrite_urls() -> None:
    # The fallback provider must stay site-agnostic: per-site knowledge
    # belongs in that site's own provider.
    url = "https://drive.google.com/file/d/abc123/view"
    assert GenericProvider().normalize(url) == url
