from __future__ import annotations

import pytest

from doc_dl.config import StatePaths
from doc_dl.errors import DocDlError
from doc_dl.providers.registry import ProviderRegistry
from doc_dl.providers.scribd import ScribdProvider, _clean_scribd_title


def test_scribd_provider_normalizes_both_url_styles() -> None:
    provider = ScribdProvider()
    assert provider.normalize("https://www.scribd.com/doc/12345/a-title") == (
        "https://www.scribd.com/document/12345"
    )
    assert provider.browser_url("https://www.scribd.com/document/12345/a-title") == (
        "https://www.scribd.com/embeds/12345/content"
    )


def test_clean_scribd_title_strips_site_suffix() -> None:
    assert (
        _clean_scribd_title("Autogenerated 10-Page Scribd Document | PDF | Scribd | Document")
        == "Autogenerated 10-Page Scribd Document"
    )


def test_clean_scribd_title_unescapes_entities() -> None:
    assert _clean_scribd_title("Alice &amp; Bob | PDF | Scribd | Document") == "Alice & Bob"


def test_clean_scribd_title_returns_none_for_empty_result() -> None:
    assert _clean_scribd_title("   ") is None


class _FakeResponse:
    def __init__(self, ok: bool, text: str) -> None:
        self.ok = ok
        self._text = text

    def text(self) -> str:
        return self._text


class _FakeRequest:
    def __init__(self, response: _FakeResponse) -> None:
        self._response = response
        self.calls: list[str] = []

    def get(self, url: str, *, timeout: float) -> _FakeResponse:
        del timeout
        self.calls.append(url)
        return self._response


class _FakePage:
    def __init__(self, url: str, response: _FakeResponse) -> None:
        self.url = url
        self.request = _FakeRequest(response)


def test_page_title_fetches_real_document_page_title() -> None:
    provider = ScribdProvider()
    page = _FakePage(
        "https://www.scribd.com/embeds/959028055/content",
        _FakeResponse(True, "<title>Ten Page Sample | PDF | Scribd | Document</title>"),
    )

    assert provider.page_title(page) == "Ten Page Sample"
    assert page.request.calls == ["https://www.scribd.com/document/959028055"]


def test_page_title_returns_none_on_failed_response() -> None:
    provider = ScribdProvider()
    page = _FakePage(
        "https://www.scribd.com/embeds/959028055/content",
        _FakeResponse(False, ""),
    )

    assert provider.page_title(page) is None


def test_page_title_returns_none_for_non_scribd_url() -> None:
    provider = ScribdProvider()
    page = _FakePage("https://example.com/not-scribd", _FakeResponse(True, "<title>x</title>"))

    assert provider.page_title(page) is None


def test_registry_prefers_scribd_over_generic() -> None:
    provider = ProviderRegistry().select("https://www.scribd.com/document/12345/a-title")
    assert provider.name == "scribd"


def test_profile_name_cannot_escape_state_root(tmp_path) -> None:
    paths = StatePaths(tmp_path)
    with pytest.raises(DocDlError) as raised:
        paths.profile("scribd", "../../escape")
    assert raised.value.identifier == "invalid_arguments"
